# Source https://github.com/okteto/go-api-docker-compose/tree/main/.github/workflows

name: MyPrueba

on: 
  push:


jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
  
    - name: Deploy application
      uses: devtomio/action-railway@v1.1.4
      with:
            railway_token: ${{ secrets.RAILWAY_TOKEN }}
        
        
        
